apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-pr
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: bdecoste
        repo: vcluster-deploy  
        labels:
        - deploy
  template:
    metadata:
      name: 'vcluster-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: https://github.com/bdecoste/vcluster-deploy.git
        targetRevision: main
        path: instance
        kustomize:
          patches:
            - patch: |-
                - op: add
                  path: /metadata/labels/vclusterName
                  value: test-pr-{{number}}-vcluster
                - op: add
                  path: /metadata/labels/prNumber
                  value: '{{number}}'
                - op: add
                  path: /metadata/labels/headBranch
                  value: '{{branch}}'
              target:
                kind: VirtualClusterInstance
                name: test
                namespace: p-demo
      project: demo
      destination:
        server: https://kubernetes.default.svc
        namespace: p-demo
