apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: vcluster-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    kind: PersistentVolumeClaim
    name: data-test-0
    namespace: loft-demo-v-test
  hostPath:
    path: /tmp/data-test-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  volumeMode: Filesystem
